<template lang="md">
Welcome to 4EVERLAND. Please read on to learn the rules and restrictions that govern your use of our website(s), products, services, and applications. If you have any questions, comments, or concerns regarding these terms or the services, please contact us at contact@4everland.org.
These Terms of Use (the “Terms”) are a binding contract between you and 4EVERLAND Foundation. You must agree to and accept all of the Terms, or you don’t have the right to use the Services. You’re using the Services in any way means that you agree to all of these Terms, and these Terms will remain in effect while you use the Services. These Terms include the provisions in this document, as well as those in the Privacy Policy and Copyright Dispute Policy (https://4EVERLAND.org/privacy-policy).
NOTICE: Please read these Terms carefully. They cover important information about Services provided to you and any charges, taxes, and fees we bill you. These Terms include information about future changes to these Terms, limitations of liability, a class action waiver, and resolution of disputes by arbitration instead of in court.
We are constantly trying to improve our Services, so these Terms may need to change along with the Services. We reserve the right to change the Terms at any given time. We will bring it to your notice via an update on the 4everland.org website, email notification, or through some other means.
If you don’t agree with the new Terms, you are free to reject them; unfortunately, that means you will no longer be able to use the services. If you use the services in any way after a change to the terms is effective, that means you agree to all of the changes.

What are the basics of using 4EVERLAND?
You are required to authorize login to your GitHub account. You may not transfer your account to anyone else without our prior written permission. You represent and warrant that you are of legal age to form a binding contract (or if not, you’ve received your parents or guardian’s permission and agreement to use the Services).
If you’re agreeing to these Terms on behalf of an organization or entity, you represent and warrant that you are authorized to agree to these Terms on behalf of your organization or entity’s and bind them to these Terms (in which case, the references to “you” and “your” in these Terms, except for in this sentence, refer to that organization or entity).
You will only use the Services for your own personal use, not on behalf of or for the benefit of any third-party, and only in a manner that complies with all the laws that apply to you.
If your use of the Services is prohibited by applicable laws, then you aren’t authorized to use the Services. We can’t and won’t be responsible for your using the services in a way that breaks the law.
You will not share your account or password with anyone, and you must protect the security of your account and your password. You’re responsible for any activity associated with your account.
Consent to receive a periodic message.
As part of the Services, you may receive communications about the offers and updates, via e-mail. By subscribing to the services, you agree to receive communications from 4EVERLAND, and agree to indemnify and hold 4EVERLAND harmless from and against any and all claims, liabilities, damages (actual and consequential), losses, and expenses (including attorneys’ fees) arising from or in any way related to your breach of the foregoing.
Your use of the Services is subject to the following additional restrictions:
You represent, warrant, and agree that you will not contribute any Content or User Submission (each of those terms is defined below) or otherwise use the Services or interact with the Services in a manner that:
(a) Infringes or violates the intellectual property rights or any other rights of anyone else;
(b) Violates any law or regulation, including, without limitation, any applicable export control laws;
(c) Is harmful, fraudulent, deceptive, threatening, harassing, defamatory, obscene, or otherwise objectionable;
(d) Jeopardizes the security of your 4EVERLAND account or anyone else’s (such as allowing someone else to log in to the Services as you);
(e) Attempts, in any manner, to obtain the password, account, or other security information from any other user;
(f) Violates the security of any computer network, or cracks any passwords or security encryption codes;
(g) Runs Mail list, Listserv, any form of auto-responder or “spam” on the Services, or any processes that run or are activated while you are not logged into the Services, or that otherwise interfere with the proper working of the Services (including by placing an unreasonable load on the Service’s infrastructure);
(h) “Crawls,” “scrapes,” or “spiders” any page, data, or portion of or relating to the Services or Content (through use of manual or automated means);
(i) Copies or stores any significant portion of the Content;
(j) Decompiles, reverse engineers or otherwise attempts to obtain the source code or underlying ideas or information of or relating to the Services.
A violation of any of the foregoing is grounds for termination of your right to use or access the Services.
What are my rights in the Services?
The materials displayed or performed or available on or through the Services, including, but not limited to, text, graphics, data, articles, photos, images, illustrations, User Submissions, and so forth (all of the foregoing, the “Content”) are protected by copyright and/or other intellectual property laws.
You promise to abide by all copyright notices, trademark rules, information, and restrictions contained in any Content you access through the Services, and you won’t use, copy, reproduce, modify, translate, publish, broadcast, transmit, distribute, perform, upload, display, license, sell, commercialize or otherwise exploit for any purpose any Content not owned by you, (i) without the prior consent of the owner of that Content or (ii) in a way that violates someone else’s (including Terminal’s) rights. You understand that 4EVERLAND owns the Services. You won’t modify, publish, transmit, participate in the transfer or sale of, reproduce (except as expressly provided in this Section), create derivative works based on, or otherwise exploit any of the Services. The Services may allow you to copy or download certain Content; please remember that just because this functionality exists, doesn’t mean that all the restrictions above don’t apply – they do!
Do I have to grant any licenses to 4EVERLAND or to other users?
Anything you post, upload, share, store, or otherwise provide through the Services is your “User Submission.” Some User Submissions may be viewable by other users. In order to display your User Submissions on the Services, and to allow other users to enjoy them (where applicable), you grant us certain rights in those User Submissions.
Please note that all of the following licenses are subject to our Privacy Policy https://4everland.org/privacy-policy to the extent they relate to User Submissions that are also your personally-identifiable information.
For all User Submissions, you hereby grant4EVERLAND a license to translate, modify (for technical purposes, for example making sure your content is viewable on an iPhone as well as a computer) and reproduce and otherwise act with respect to such User Submissions, in each case to enable us to operate the Services, as described in more detail below. This is a license only – your ownership in User Submissions is not affected.
If you store a User Submission in your own personal 4EVERLAND account, in a manner that is not viewable by any other user except you (a “Personal User Submission”), you grant 4EVERLAND the license above, as well as a license to display, perform, and distribute your Personal User Submission for the sole purpose of making that Personal User Submission accessible to you and providing the Services necessary to do so.
If you share a User Submission only in a manner that only certain specified users can view (for example, a private message to one or more other users) (a “Limited Audience User Submission”), then you grant 4EVERLAND the licenses above, as well as a license to display, perform, and distribute your Limited Audience User Submission for the sole purpose of making that Limited Audience User Submission accessible to such other specified users, and providing the Services necessary to do so. Also, you grant such other specified users a license to access that Limited Audience User Submission and to use and exercise all rights in it, as permitted by the functionality of the Services.
If you share a User Submission publicly on the Services and/or in a manner that more than just you or certain specified users can view a “Public User Submission”), then you grant 4EVERLAND the licenses above, as well as a license to display, perform, and distribute your Public User Submission for the purpose of making that Public User Submission is accessible to all 4EVERLAND users and providing the Services necessary to do so, as well as all other rights necessary to use and exercise all rights in that Public User Submission in connection with the Services and/or otherwise in connection with Terminal’s business. Also, you grant all other users of the Services a license to access that Public User Submission and to use and exercise all rights in it, as permitted by the functionality of the Services.
You agree that the licenses you grant are royalty-free, perpetual, sub licensable, irrevocable, and worldwide.
Finally, you understand and agree that 4EVERLAND, in performing the required technical steps to provide the Services to our users (including you), may need to make changes to your User Submissions to conform and adapt those User Submissions to the technical requirements of connecting networks, devices, services, or media, and the foregoing licenses include the rights to do so.
What if I see something on the Services that infringes my copyright?
You may have heard of the Digital Millennium Copyright Act (the “DMCA”), as it relates to online service providers, like 4EVERLAND, being asked to remove material that allegedly violates someone’s copyright. We respect others’ intellectual property rights, and we reserve the right to delete or disable Content alleged to be infringing, and to terminate the accounts of repeat alleged infringers; to review our complete Copyright Dispute Policy and learn how to report potentially infringing content, click here https://4EVERLAND.org/privacy-policy. To learn more about the DMCA, click here http://www.copyright.gov/legislation/dmca.pdf
Who is responsible for what I see and do on the Services?
Any information or content publicly posted or privately transmitted through the Services is the sole responsibility of the person from whom such content originated, and you access all such information and content at your own risk, and we aren’t liable for any errors or omissions in that information or content or for any damages or loss you might suffer in connection with it. We cannot control and have no duty to take any action regarding how you may interpret and use the Content or what actions you may take as a result of having been exposed to the Content, and you hereby release us from all liability for you having acquired or not acquired Content through the Services. We can’t guarantee the identity of any users with whom you interact in using the Services and are not responsible for which users gain access to the Services. You are responsible for all Content you contribute, in any manner, to the Services, and you represent and warrant you have all rights necessary to do so, in the manner in which you contribute it. You will keep all your registration information accurate and current. You are responsible for all your activity in connection with the Services.
The Services may contain links or connections to third-party websites or services that are not owned or controlled by 4EVERLAND. When you access third-party websites or use third-party services, you accept that there are risks in doing so and that 4EVERLAND is not responsible for such risks. We encourage you to be aware when you leave the Services and to read the terms and conditions and privacy policy of each third-party website or service that you visit or utilize.
4EVERLAND has no control over and assumes no responsibility for, the content, accuracy, privacy policies, or practices of or opinions expressed on any third-party websites or by any third-party that you interact with through the Services. In addition, 4EVERLAND will not and cannot monitor, verify, censor, or edit the content of any third-party site or service. By using the Services, you release and hold us harmless from any and all liability arising from your use of any third-party website or service.
Your interactions with organizations and/or individuals found on or through the Services, including payment and delivery of goods or services, and any other terms, conditions, warranties, or representations associated with such dealings, are solely between you and such organizations and/or individuals. You should make whatever investigation you feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties. You agree that 4EVERLAND shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings.
If there is a dispute between participants on this site, or between users and any third-party, you agree that 4EVERLAND is under no obligation to become involved. In the event that you have a dispute with one or more other users, you release 4EVERLAND, its directors, officers, employees, agents, and successors from claims, demands, and damages of every kind or nature, known or unknown, suspected or unsuspected, disclosed or undisclosed, arising out of or in any way related to such disputes and/or our Services.
Will 4EVERLAND ever change the Services?
We’re always trying to improve the Services, so they may change over time. We may suspend or discontinue any part of the Services, or we may introduce new features or impose limits on certain features or restrict access to parts or all of the Services. We reserve the right to remove any Content from the Services at any time, for any reason (including, but not limited to, if someone alleges you contributed that Content in violation of these Terms), in our sole discretion, and without notice.
Do the Services cost anything?
The Services may be free or we may charge a fee for using the Services. If you are using a free version of the Services, we will notify you before any Services you are then using begin carrying a fee, and if you wish to continue using such Services, you must pay all applicable fees for such Services. Note that if you elect to receive text messages through the Services, data and message rates may apply. Any and all such charges, fees, or costs are your sole responsibility. You should consult with your wireless carrier to determine what rates, charges, fees, or costs may apply to your use of the Services.
a. Paid Services. Certain of our Services may be subject to payments now or in the future (the “Paid Services”). Please see our Paid Services page for a description of the current Paid Services. Please note that any payment terms presented to you in the process of using or signing up for a Paid Service are deemed part of these Terms.
b. Billing. We use a third-party payment processor (the “Payment Processor”) to bill you through a payment account linked to your account on the Services (your “Billing Account”) for use of the Paid Services. The processing of payments will be subject to the terms, conditions, and privacy policies of the Payment Processor in addition to these Terms. We are not responsible for errors by the Payment Processor. By choosing to use Paid Services, you agree to pay us, through the Payment Processor, all charges at the prices then in effect for any use of such Paid Services in accordance with the applicable payment terms and you authorize us, through the Payment Processor, to charge your chosen payment provider (your “Payment Method”). You agree to make payment using that selected Payment Method. We reserve the right to correct any errors or mistakes that the Payment Processor makes even if it has already requested or received payment.
c. Payment Method. The terms of your payment will be based on your Payment Method and may be determined by agreements between you and the financial institution, credit card issuer, or other providers of your chosen Payment Method. If we, through the Payment Processor, do not receive payment from you, you agree to pay all amounts due on your Billing Account upon demand.
d. Recurring Billing. Some of the Paid Services may consist of an initial period, for which there is a one-time charge, followed by recurring period charges as agreed to by you. By choosing a recurring payment plan, you acknowledge that such Services have an initial and recurring payment feature and you accept responsibility for all recurring charges prior to cancellation. WE MAY SUBMIT PERIODIC CHARGES (E.G., MONTHLY) WITHOUT FURTHER AUTHORIZATION FROM YOU UNTIL YOU PROVIDE PRIOR NOTICE (RECEIPT OF WHICH IS CONFIRMED BY US) THAT YOU HAVE TERMINATED THIS AUTHORIZATION OR WISH TO CHANGE YOUR PAYMENT METHOD. SUCH NOTICE WILL NOT AFFECT CHARGES SUBMITTED BEFORE WE REASONABLY COULD ACT. TO TERMINATE YOUR AUTHORIZATION OR CHANGE YOUR PAYMENT METHOD, GO TO ACCOUNT SETTINGS.
e. Current Information Required. YOU MUST PROVIDE CURRENT, COMPLETE, AND ACCURATE INFORMATION FOR YOUR BILLING ACCOUNT. YOU MUST PROMPTLY UPDATE ALL INFORMATION TO KEEP YOUR BILLING ACCOUNT CURRENT, COMPLETE AND ACCURATE (SUCH AS A CHANGE IN BILLING ADDRESS, CREDIT CARD NUMBER, OR CREDIT CARD EXPIRATION DATE), AND YOU MUST PROMPTLY NOTIFY US OR OUR PAYMENT PROCESSOR IF YOUR PAYMENT METHOD IS CANCELED (E.G., FOR LOSS OR THEFT) OR IF YOU BECOME AWARE OF A POTENTIAL BREACH OF SECURITY, SUCH AS THE UNAUTHORIZED DISCLOSURE OR USE OF YOUR USER NAME OR PASSWORD. CHANGES TO SUCH INFORMATION CAN BE MADE IN ACCOUNT SETTINGS. IF YOU FAIL TO PROVIDE ANY OF THE FOREGOING INFORMATION, YOU AGREE THAT WE MAY CONTINUE CHARGING YOU FOR ANY USE OF PAID SERVICES UNDER YOUR BILLING ACCOUNT UNLESS YOU HAVE TERMINATED YOUR PAID SERVICES AS SET FORTH ABOVE.
f. Change in Amount Authorized. If the amount to be charged to your Billing Account varies from the amount you preauthorized (other than due to the imposition or change in the amount of state sales taxes), you have the right to receive, and we shall provide, a notice of the amount to be charged and the date of the charge before the scheduled date of the transaction. Any agreement you have with your payment provider will govern your use of your Payment Method. You agree that we may accumulate charges incurred and submit them as one or more aggregate charges during or at the end of each billing cycle.
g. Reaffirmation of Authorization. Your non-termination or continued use of a Paid Service reaffirms that we are authorized to charge your Payment Method for that Paid Service. We may submit those charges for payment and you will be responsible for such charges. This does not waive our right to seek payment directly from you. Your charges may be payable in advance, in arrears, per usage, or as otherwise described when you initially selected to use the Paid Service.
Free Trials and Other Promotions. Any free trial or other promotion that provides access to a Paid Service must be used within the specified time of the trial. You must stop using a Paid Service before the end of the trial period in order to avoid being charged for that Paid Service. If you cancel prior to the end of the trial period and are inadvertently charged for a Paid Service, please contact us at contact@4everland.org
What if I want to stop using the Services?
You’re free to do that at any time, by contacting us at contact@4everland.org; please refer to our Privacy Policy 4EVERLAND.org/privacy-policy, as well as the licenses above, to understand how we treat the information you provide to us after you have stopped using our Services.4EVERLAND is also free to terminate (or suspend access to) your use of the Services or your account, for any reason in our discretion, including your breach of these Terms. 4EVERLAND has the sole right to decide whether you are in violation of any of the restrictions set forth in these Terms. Account termination may result in the destruction of any Content associated with your account, so keep that in mind before you decide to terminate your account. Provisions that, by their nature, should survive termination of these Terms shall survive termination. By way of example, all of the following will survive termination: any obligation you have to pay us or indemnify us, any limitations on our liability, any terms regarding ownership or intellectual property rights, and terms regarding disputes between us, including without limitation the arbitration agreement.
What else do I need to know?
Warranty Disclaimer. Neither 4EVERLAND nor its licensors or suppliers make any representations or warranties concerning any content contained in or accessed through the Services, and we will not be responsible or liable for the accuracy, copyright compliance, legality, or decency of material contained in or accessed through the Services. We (and our licensors and suppliers) make no representations or warranties regarding suggestions or recommendations of services or products offered or purchased through the Services. Products and services purchased or offered (whether or not following such recommendations and suggestions) through the Services are provided “AS IS” and without any warranty of any kind from 4EVERLAND or others (unless, with respect to such others only, provided expressly and unambiguously in writing by a designated third-party for a specific product).
Assignment. You may not assign, delegate or transfer these Terms or your rights or obligations hereunder, or your Services account, in any way (by operation of law or otherwise) without Terminal’s prior written consent. We may transfer, assign, or delegate these Terms and our rights and obligations without consent.
Miscellaneous. You will be responsible for paying, withholding, filing, and reporting all taxes, duties, and other governmental assessments associated with your activity in connection with the Services, provided that the 4EVERLAND may, in its sole discretion, do any of the foregoing on your behalf or for itself as it sees fit. The failure of either you or us to exercise, in any way, any right herein shall not be deemed a waiver of any further rights hereunder. If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated, to the minimum extent necessary, so that these Terms shall otherwise remain in full force and effect and enforceable. You and 4EVERLAND agree that these Terms are the complete and exclusive statement of the mutual understanding between you and 4EVERLAND and that these Terms supersede and cancel all previous written and oral agreements, communications, and other understandings relating to the subject matter of these Terms. You hereby acknowledge and agree that you are not an employee, agent, partner, or joint venture of 4EVERLAND, and you do not have any authority of any kind to bind 4EVERLAND in any respect whatsoever.
</template>
<style scoped>
p {
  word-break: break-word;
  font-size: 14px;
  line-height: 1.5;
  margin-bottom: 30px;
}
</style>
